apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: pacman
  labels:
    name: pacman
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31111
  selector:
    name: pacman