apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pacman
  name: pacman
  namespace: pacman
spec:
  replicas: 1
  selector:
    name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: quay.io/ifont/pacman-nodejs-app
        name: web
        ports:
        - containerPort: 8080
          name: http-server
        env:
        - name: MONGO_SERVICE_HOST
          value: "mongo"
        - name: MONGO_DATABASE
          value: "pacman"
        - name: MY_MONGO_PORT
          value: "27017"
        - name: MONGO_USE_SSL
          value: "false"
        - name: MONGO_VALIDATE_SSL
          value: "false"          