apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pc-mongo-pvc
  namespace: pacman  
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
